### ISSUE TITLE
parsedmarc-1 don't start

### ISSUE THREAD

**Issue by LMarly** [patschi/parsedmarc-dockerized#37]
Hello all,

When I start the project, the container parsedmarc-1 don't start
When I go in the logs I see that : 

```shell

2024-04-08 09:41:27   Traceback (most recent call last):
2024-04-08 09:41:27   File "/opt/pypy/lib/pypy3.10/site-packages/parsedmarc/cli.py", line 1211, in _main
2024-04-08 09:41:27     mailbox_connection = IMAPConnection(
2024-04-08 09:41:27   File "/opt/pypy/lib/pypy3.10/site-packages/parsedmarc/mail/imap.py", line 24, in __init__
2024-04-08 09:41:27     self._client = IMAPClient(host, user, password, port=port,
2024-04-08 09:41:27   File "/opt/pypy/lib/pypy3.10/site-packages/mailsuite/imap.py", line 151, in __init__
2024-04-08 09:41:27     imapclient.IMAPClient.__init__(self,
2024-04-08 09:41:27   File "/opt/pypy/lib/pypy3.10/site-packages/imapclient/imapclient.py", line 288, in __init__
2024-04-08 09:41:27     self._imap = self._create_IMAP4()
2024-04-08 09:41:27   File "/opt/pypy/lib/pypy3.10/site-packages/imapclient/imapclient.py", line 325, in _create_IMAP4
2024-04-08 09:41:27     return tls.IMAP4_TLS(
2024-04-08 09:41:27   File "/opt/pypy/lib/pypy3.10/site-packages/imapclient/tls.py", line 44, in __init__
2024-04-08 09:41:27     imaplib.IMAP4.__init__(self, host, port)
2024-04-08 09:41:27   File "/opt/pypy/lib/pypy3.10/imaplib.py", line 202, in __init__
2024-04-08 09:41:27     self.open(host, port, timeout)
2024-04-08 09:41:27   File "/opt/pypy/lib/pypy3.10/site-packages/imapclient/tls.py", line 52, in open
2024-04-08 09:41:27     sock = socket.create_connection(
2024-04-08 09:41:27   File "/opt/pypy/lib/pypy3.10/socket.py", line 824, in create_connection
2024-04-08 09:41:27     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2024-04-08 09:41:27   File "/opt/pypy/lib/pypy3.10/socket.py", line 955, in getaddrinfo
2024-04-08 09:41:27     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2024-04-08 09:41:27 _socket.gaierror: [Errno -2] Name or service not known
2024-04-08 09:42:28    ERROR:cli.py:1223:IMAP Error

``` 

I'm working on the version v4.28.0 on docker desktop on windows 11.
Do you have any idea of how to solve this problem ?

**Comment by sdonchez** [comment]
I'm guessing from the timestamp gap that you addressed the first issue here - The config.ini not existing. (if not, look at the README - it prompts you to copy the example over)

Assuming you've done that, and edited the file to suit your implementation, it looks like the credentials in said file for email access aren't valid. I would double check them against whatever account you're routing dmarc reports to, and keep in mind that gmail, as well as others, no longer support direct imap access with the account credentials, but need you to setup an app password. (I just re-learned this the hard way while setting up this stack)
